name: Homebrew

on:
  push:
    branches: [action]

env:
  CARGO_TERM_COLOR: always


jobs:
  test-homebrew:
    runs-on: macos-latest
    steps:
      - name: Bump formulae
        uses: Homebrew/actions/bump-formulae@master
        with:
          # Custom GitHub access token with only the 'public_repo' scope enabled
          token: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
          # Bump only these formulae if outdated
          formulae: |
            hg-tui
