name: Homebrew

on:
  push:
    branches: [action]

env:
  CARGO_TERM_COLOR: always


jobs:
  test-homebrew:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Homebrew bump formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          # Required, custom GitHub access token with the 'public_repo' and 'workflow' scopes
          token: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
          # Optional, defaults to homebrew/core
          tap: kaixinbaba/hg-tui
          # Formula name, required
          formula: hg-tui
          force: true
