name: Homebrew

on:
  push:
    branches: [action]

env:
  CARGO_TERM_COLOR: always


jobs:
  test-homebrew:
    runs-on: macos-latest
    steps:
      - name: Homebrew bump formula
        uses: dawidd6/action-homebrew-bump-formula@v3.8.0
        with:
          # Required, custom GitHub access token with the 'public_repo' and 'workflow' scopes
          token: ${{secrets.HOMEBREW_API_TOKEN}}
          tap: kaixinbaba/hg-tui
          formula: hg-tui
